### PR TITLE
Update yumrepo.gemspec

### PR DESCRIPTION
**Pull request by vinayakvakkund**
Updating the version to 0.2.2 
To get these changes, https://github.com/rubiojr/yumrepo/pull/6

### CODE REVIEW

**Comment by rubiojr** [comment]
@vinayakvakkund thanks!

I don't have plans to maintain this gem going forward, but I can grant you access to https://rubygems.org/gems/yumrepo if you want, so you can bump it yourself. Let me know.

**Comment by vinayakvakkund** [comment]
Thanks @rubiojr , I am fine with that.

Could you please upload new gem to rubygems repo?

**Comment by vinayakvakkund** [comment]
Hi @rubiojr  , Could You please upload new RPM to the repository?

**Comment by rubiojr** [comment]
@vinayakvakkund email me your rubygems account/email and I'll grant you access to be able to push it yourself, can't guarantee I'll be able to do that this week.

**Comment by rubiojr** [comment]
Maybe there's a workflow we can add to this repo to automatically push gems every new release?

**Comment by vinayakvakkund** [comment]
> Maybe there's a workflow we can add to this repo to automatically push gems every new release?

Yeah sure we can do that, I am not sure how to do it from Github but as of now I can build gem manually and upload it to rubygems. Please find below details of my username / email
 usrername : vinayak3700
email: vinayak3700ssbj@gamil.com

**Comment by rubiojr** [comment]
done.

**Pull request merged**
